### ISSUE TITLE
中文乱码问题

### ISSUE THREAD

**Issue by Shawn-zhao** [xiaweizi/AndroidToolsExample#3]
使用json格式的sample data时，中文乱码，把json编码改为了utf-8还是没有用。
![tim 20180301135413](https://user-images.githubusercontent.com/5833053/36829047-37e7827c-1d58-11e8-8262-3015b32ace03.png)

![123](https://user-images.githubusercontent.com/5833053/36829128-8caced06-1d58-11e8-989c-73464aaef877.png)

**Comment by xiaweizi** [comment]
我觉得是不是还是文件编码的原因？
1. 创建新的空 json 文件，编码格式改成 utf-8
2. 将数据拷贝进去

运行一下，如果还是不行，那就把源码发我一下，我这边没出现这个问题。。。

**Comment by PawnXIE** [comment]
Windows下git clone 下来中文就乱码，自己新建文件粘贴进去还是不行，用Ubuntu虚拟机clone下来测试中文没问题。。。坑啊

**Comment by PawnXIE** [comment]
继续测试，应该是Android Studio 3.1.2 Windows版本（不知3.0.1和3.1是否也是乱码）的问题，在Android Studio 2.3.2里看不是乱码，也不知道谷歌魔改了啥导致的，等修复吧
